# This example is very similar to one I use.

http:
  AdGuard:
    cert: example.com
    options:
      block_exploits: true
      force_tls: true
      http2_support: true
    # Example showing default and alternative subdomain.
    subdomains:
      - adguard
      - dns
    upstream:
      host: adguard
      port: 3000
  Blocky:
    cert: example.com
    upstream:
      host: blocky
      port: 4000
  Blocky (disable):
    cert: example.com
    redirect: https://blocky.example.com/api/blocking/disable
  Blocky (enable):
    cert: example.com
    redirect: https://blocky.example.com/api/blocking/enable
  Blocky (status):
    cert: example.com
    redirect: https://blocky.example.com/api/blocking/status
  default:
    cert: example.com
    options:
      block_exploits: true
      force_tls: true
      http2_support: true
    root: /nap/www
  Gitea:
    cert: example.com
    options:
      block_exploits: true
      force_tls: true
      http2_support: true
    # Example showing alternative subdomain.
    subdomains:
      - git
    upstream:
      host: gitea
      port: 3000
  Grafana:
    cert: example.com
    options:
      block_exploits: true
      force_tls: true
      http2_support: true
    upstream:
      host: grafana
      port: 3000
  # Good example of a container utilizing subpaths.
  Guac:
    cert: example.com
    locations:
      guacamole:
        upstream:
          host: guac
          port: 8080
    options:
      block_exploits: true
      force_tls: true
      http2_support: true
    redirect: /guacamole
  Syncthing:
    cert: example.com
    options:
      block_exploits: true
      force_tls: true
      http2_support: true
    upstream:
      host: syncthing
      port: 8384

pki:
  default:
    certs:
      - example.com:*.example.com
