# This example shows how to use a BYOC cert like Let's Encrypt.

http:
  default:
    # You will need to mount your certs directory to /byoc and ensure
    # you've renamed the cert and key to example.com.chain.pem and
    # example.com.key.pem.
    cert: byoc/example.com
    root: /nap/www
