name: GitHub Container Registry
on:
  push:
    tags: ["v*.*.*"]
  schedule:
    - cron: "0 4 * * 0"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Fetch tags
        run: git pull --tags origin main
      - name: Format latest tag for Docker
        run: |
          git log --pretty=tformat:"%h %s" | head -n 1
          t="$(git tag -l | sort -V | tail -n 1)"
          echo "LVER=$t" | tee -a "$GITHUB_ENV"
          echo "SVER=${t%%.*}" | tee -a "$GITHUB_ENV"
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          password: ${{secrets.GITHUB_TOKEN}}
          registry: ghcr.io
          username: ${{github.actor}}
      - uses: docker/build-push-action@v4
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: .
          pull: true
          push: true
          tags: |
            ghcr.io/${{github.repository}}:latest
            ghcr.io/${{github.repository}}:${{env.SVER}}
            ghcr.io/${{github.repository}}:${{env.LVER}}
