name: GitHub Container Registry
on:
  push:
    tags: ["v*.*.*"]
  schedule:
    - cron: "0 4 * * 1"
env:
  IMAGE_NAME: ${{github.repository}}
  REGISTRY: ghcr.io
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          password: ${{secrets.GITHUB_TOKEN}}
          registry: ${{env.REGISTRY}}
          username: ${{github.actor}}
      - name: Create short version tag
        if: github.ref_type == 'tag'
        run: |
          t=${{github.ref_name}}
          echo "SHORT_VER=${t%%.*}" >>"$GITHUB_ENV"
      - uses: docker/build-push-action@v4
        if: github.ref_type == 'tag'
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: .
          pull: true
          push: true
          tags: |
            ${{env.REGISTRY}}/${{env.IMAGE_NAME}}:latest
            ${{env.REGISTRY}}/${{env.IMAGE_NAME}}:${{env.SHORT_VER}}
            ${{env.REGISTRY}}/${{env.IMAGE_NAME}}:${{github.ref_name}}
